core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('movies/<int:pk>/', views.MovieDetail.as_view(), name='movie-detail'),
    path('movies/', views.MovieList.as_view(), name='movie-list'),
    path('movie/<int:movie_id>/vote/', views.CreateVote.as_view(),
         name='create-vote'),
    path('movie/<int:movie_id>/vote/<int:pk>/', views.UpdateVote.as_view(),
         name='update-vote'),
]

imdb/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls
import user.urls

handler404 = 'imdb.views.handler404'
handler500 = 'imdb.views.handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),
]

core/models.py
from django.db import models
from django.conf import settings
from django.db.models.aggregates import Sum


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__vote'))
        return qs


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(movie=movie,
                        user=user)


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{} {} ({} - {})'.format(
                self.first_name,
                self.last_name,
                self.born.born,
                self.died.died
            )
        else:
            return '{} {} ({})'.format(
                self.first_name,
                self.last_name,
                self.born.born
            )

    @property
    def full_name(self):
        return '{} {}'.format(
            self.first_name,
            self.last_name
        )


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audience'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),
    )
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS,
                                 default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField()
    director = models.ForeignKey(to=Person,
                                 related_name='directed',
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True)
    writers = models.ManyToManyField(to=Person,
                                     related_name='writing_credits',
                                     blank=True)
    actors = models.ManyToManyField(to=Person,
                                    through='Role',
                                    related_name='acting_credits',
                                    blank=True)
    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} {}'.format(self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(to=Movie,
                              on_delete=models.DO_NOTHING)
    person = models.ForeignKey(to=Person,
                               on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id,
                                 self.person_id,
                                 self.name)

    class Meta:
        unique_together = ('movie',
                           'person',
                           'name')


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VOTE_CHOICES = (
        (UP, 'THUMBS UP'),
        (DOWN, 'THUMBS DOWN'),
    )
    movie = models.ForeignKey(to=Movie,
                              on_delete=models.CASCADE)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    vote = models.SmallIntegerField(choices=VOTE_CHOICES)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ('movie', 'user')

    def __str__(self):
        return '{} {} {}'.format(
            self.movie,
            self.person.full_name,
            self.choice
        )

core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Vote, Movie


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ('vote', 'user', 'movie')

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    vote = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VOTE_CHOICES
    )

core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView)
from django.urls import reverse
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied

from .models import Movie, Person, Vote
from .forms import VoteForm


class MovieList(ListView):
    model = Movie
    context_object_name = 'movies'  # Default: object_list
    paginate_by = 10
    template_name = 'core/movie_list.html'  # Default: <app_label>/<model_name>_list.html
    queryset = Movie.objects.all()  # Default: Movie.objects.all()


class MovieDetail(DetailView):
    """Provides the detail response of the movies"""
    queryset = Movie.objects.all_with_related_persons_and_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                user=self.request.user,
                movie=self.object
            )
            if vote.id:
                vote_form_url = reverse(
                    'core:update-vote',
                    kwargs={
                        'movie_id': vote.movie.id,
                        'pk': vote.id})
            else:
                vote_form_url = reverse(
                    'core:create-vote',
                    kwargs={
                        'movie_id': self.object.id,
                    }
                )
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:movie-detail',
            kwargs={
                'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:movie-detail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    model = Vote
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
                'cannot change another user\'s vote'
            )
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:movie-detail',
            kwargs={
                'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:movie-detail',
            kwargs={'pk': movie_id}
        )
        return redirect(to=movie_detail_url)

core/templates/core/movie_detail.html
{% extends 'base.html' %} 
{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>{{ object }}</h1>
<p class="lead">{{object.plot }}</p>
{% endblock %}

{% block sidebar %}
<div>
    <span class="badge badge-primary">
        {{ object.get_rating_display }}
    </span>
</div>
<div>
    <h2>
        Score: {{ object.score | default_if_none:"TBD" }}
    </h2>
</div>
<div>
    {% if vote_form %}
    <form action="{{ vote_form_url }}" method="POST">
        {% csrf_token %}
        {{ vote_form.as_p }}
        <button class="btn btn-primary">
            Vote
        </button>
    </form>
    {% else %}
        <p>Login to vote for this movie</p>
    {% endif %}
</div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
  All The Movies
{% endblock %}

{% block main %}
  <ul >
    {% for movie in movies %}
      <li >
        <a href="{% url 'core:movie-detail' pk=movie.id %}" >
          {{ movie }}
        </a >
      </li >
    {% endfor %}
  </ul >
  {% if is_paginated %}
    <nav >
      <ul class="pagination" >
        <li class="page-item" >
          <a
            href="{% url 'core:movie-list' %}?page=1"
            class="page-link"
          >
            First
          </a >
        </li >
        {% if page_obj.has_previous %}
          <li class="page-item" >
            <a
              href="{% url 'core:movie-list' %}?page={{ page_obj.previous_page_number }}"
              class="page-link"
            >
              {{ page_obj.previous_page_number }}
            </a >
          </li >
        {% endif %}
        <li class="page-item active" >
          <a
            href="{% url 'core:movie-list' %}?page={{ page_obj.number }}"
            class="page-link"
          >
            {{ page_obj.number }}
          </a >
        </li >
        {% if page_obj.has_next %}
          <li class="page-item" >
            <a
              href="{% url 'core:movie-list' %}?page={{ page_obj.next_page_number }}"
              class="page-link"
            >
              {{ page_obj.next_page_number }}
            </a >
          </li >
        {% endif %}
        <li class="page-item" >
          <a
            href="{% url 'core:movie-list' %}?page=last"
            class="page-link"
          >
            Last
          </a >
        </li >
      </ul >
    </nav >
  {% endif %}
{% endblock %}

core/templates/core/person_detail.html
{% extends 'base.html'}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}
    <h1>{{ object }}</h1>
    <h2>Actor</h2>
    <ul>
        {% for role in object.role_set.all %}
        <li>
            <a href="{% url 'core:movie-detail' role.movie.id %}">{{role.movie}}</a>: {{role.name}}</li>
        {% endfor %}
    </ul>

    <h2>Writer</h2>
    <ul>
        {% for role in object.writing_credits.all %}
        <li>
            <a href="{% url 'core:movie-detail' role.movie.id %}">{{role.movie}}</a>: {{role.name}}</li>
        {% endfor %}
    </ul>

    <h2>Director</h2>
    <ul>
        {% for role in object.directed.all %}
        <li>
            <a href="{% url 'core:movie-detail' role.movie.id %}">{{role.movie}}</a>: {{role.name}}</li>
        {% endfor %}
    </ul>

{% endblock %}